import type { Project } from '@/types/portfolio';

// This file is auto-generated by running "npm run update-projects"
// Do not edit manually unless you know what you're doing.

export const projectsData: Project[] = [
  {
    id: 1,
    name: "ProYodha",
    description: "Architected an event-driven esports platform and career marketplace. Engineered a decoupled Go and AWS (SQS/SNS) microservices backend processing 100,000+ daily events and handling 10,000+ concurrent connections with strictly <50ms latency.",
    demo_url: "https://www.proyodha.com/landing", 
    image: "https://images.unsplash.com/photo-1542751371-adc38448a05e?q=80&w=2070&auto=format&fit=crop", // Placeholder esports image
    language: "Go, TypeScript, Dart",
    stargazers_count: 0,
    forks_count: 0
  },
  {
    id: 2,
    name: "Connectopia",
    description: "Spearheaded the end-to-end development of a one-to-one communication web application, integrating user authentication, profile management, and secure messaging features. Designed and deployed a scalable RESTful API using Express, achieving a 30% improvement in data retrieval speed. Implemented a real-time chat feature using WebSocket and Socket.io, enhancing user engagement and reducing response time by 20%.",
    html_url: "https://github.com/Dustu103/Connectopia", // Assuming this from previous github username
    language: "React, Express, MongoDB",
    stargazers_count: 0,
    forks_count: 0
  }
];
